### ISSUE TITLE
monitor feeds

### ISSUE THREAD

**Issue by gubuntu** [kartoza/gfdrr_oondra#19]
- view status of feeds

**Comment by gubuntu** [comment]
Configure Prometheus to monitor service and feed status on http://oondra.kartoza.com/. Deploy Prometheus master on mountain and then configure a Prometheus (host and Django) client for OONDRA. This will be a good test case for Kartoza and is a deliverable for OONDRA. 

Highest priority for first thing Monday morning @rischanlab please.

**Comment by rischanlab** [comment]
Hi @gubuntu @cchristelis 

I have tried in my local machine inside the docker-machine to run prometheus with Gravana
Inside my docker-machine I run docker-osm containers. The result below:

**Docker host monitoring:**

![screen shot 2016-10-31 at 12 18 44 pm](https://cloud.githubusercontent.com/assets/2235894/19845098/2eda2098-9f66-11e6-84e9-5a357ffd232b.png)
1. Server uptime, CPU idle percent, number of CPU cores, available memory, swap and storage
2. System load average graph, running and blocked by IO processes graph, interrupts graph
3. CPU usage graph by mode (guest, idle, system, user)
4. Memory usage graph by distribution (used, free, buffers, cached)
5. IO usage graph
6. Network usage graph by device (inbound Bps, Outbound Bps)
7. Swap usage and activity graphs

**Docker containers monitoring:**

![screen shot 2016-10-31 at 12 17 46 pm](https://cloud.githubusercontent.com/assets/2235894/19845107/3d1a3562-9f66-11e6-8435-c8de649d509e.png)
![screen shot 2016-10-31 at 12 18 16 pm](https://cloud.githubusercontent.com/assets/2235894/19845109/4002ee22-9f66-11e6-98bb-3ecf7b4832aa.png)
1. Total containers CPU load, memory and storage usage
2. Running containers graph, system load graph, IO usage graph
3. Container CPU usage graph
4. Container memory usage graph
5. Container cached memory usage graph
6. Container network inbound usage graph
7. Container network outbound usage graph

Hi @gubuntu my Question is, as I understand this prometheus can run in the host (ex: Kartoza5), but it seems this service will monitor all containers inside the kartoza5 not only for gfdrr containers? 

How about our purpose? do we need to monitor all containers inside the host? or only for one project. Because in the host (ex: kartoza5) we dont have a docker-machine. All containers run in the same docker host. 

Thank you.

**Comment by gubuntu** [comment]
Monitor everything on the host. (default) Please comment on progress.

**Comment by rischanlab** [comment]
Hi @gubuntu the ping result of monitor.kartoza.com is 104.27.136.153. It seems that domain does not pointed to mountain. 

The progress:

I have installed Prometheus on mountain, please login to http://196.214.55.116:3000/

Username : admin
Password : kartoza

I already setup monitoring system for two servers which are Mountain and Kartoza5. 
Press home button to see all stuff which available on the monitoring system. 

![screen shot 2016-11-22 at 6 11 48 am](https://cloud.githubusercontent.com/assets/2235894/20504651/2975e22e-b07b-11e6-8ee0-67a513dab487.png)

## Mountain docker host monitoring
![mountain-docker-host](https://cloud.githubusercontent.com/assets/2235894/20504738/b11936d6-b07b-11e6-8dbb-cb71309520f3.png)

## Kartoza5 docker host monitoring 
![kartoza5-docker-host](https://cloud.githubusercontent.com/assets/2235894/20504749/bde35e3c-b07b-11e6-946e-0698a1deb5c0.png)

## Mountain docker-containers monitoring
![mountain-docker-containers](https://cloud.githubusercontent.com/assets/2235894/20504755/c6a6ce6e-b07b-11e6-97d0-febe520e9114.png)

## Kartoza5 docker-containers monitoring
![kartoza5-docker-containers](https://cloud.githubusercontent.com/assets/2235894/20504763/ceac1948-b07b-11e6-9c9a-ffdc4db01de5.png)


The problem:

I am still not able to make a dashboard and clustering the containers for each project. 

Thank you.

**Comment by rischanlab** [comment]
Hi @gubuntu May I close this issue? 

Now the monitor available on http://monitor.kartoza.com 
The monitoring systems are available for Mountain and K5 server. 

Thank you.
