### ISSUE TITLE
some layers not drawing and no thumbnails working

### ISSUE THREAD

**Issue by gubuntu** [kartoza/gfdrr_oondra#43]
please fix urgently

**Comment by NyakudyaA** [comment]
The thumbnails are not working mainly because they are loaded in the db as `port 8000` instead of  the external port `port:8111`. From the database `select thumbnail_url from base_resourcebase where thumbnail_url is not null;` returns the value with incorrect ports.

Solution: we need to fix the upload script so that it has correct url

**Comment by gubuntu** [comment]
Thanks @NyakudyaA, please go ahead and fix the script and fix the layers in place.

**Comment by gubuntu** [comment]
@NyakudyaA this is fixed, right? For all layers and in load procedure and not just a workaround? Please comment and complete or close

**Comment by NyakudyaA** [comment]
All layers are working fine now. If you load a layer it will generate the correct thumbnail.
