### ISSUE TITLE
fix domains

### ISSUE THREAD

**Issue by gubuntu** [kartoza/gfdrr_oondra#54]
even though the site domain is now oondra.kartoza.com, there are links in the system with 'localhost' or 'staging' as the domains. ALL links should have oondra.kartoza.com as the domain. 

This is why thumbnails and some other funcitonality is not working. 

When are these generated and how are they maintained? It should be automated, not manual. 

e.g. see links in here

http://oondra.kartoza.com/catalogue/csw?outputschema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&service=CSW&request=GetRecordById&version=2.0.2&elementsetname=full&id=249f2902-ab28-11e6-a16d-0242ac110025

cc @lucernae (note example of single-record CSW request)
cc @Nyakudya

**Comment by NyakudyaA** [comment]
@gubuntu the reference to staging is because when the site was setup it was meant to be staging hence in the `geonode/settings.py` we specify the url that the instance will fetch. Currently this is set to `http://staging.oondra.kartoza.com:8181/geoserver/` so any metadata generated will contain that. I am not sure even if we restart oondra with the new url it will update the old url endpoints otherwise we will need to update it in the postgres database. Rebuilding geonode will ultimately affect #48.

**Comment by rischanlab** [comment]
Hi @NyakudyaA should I change the url inside the settings.py then re-build the OONDRA? 
I just worried hehee. 

Thank you

**Comment by NyakudyaA** [comment]
@rischanlab  I think you should just change the url inside the settings file and then stop and start the container. I am not sure if it will pick up the changes. I think we might need to test on our local machines then apply on oondra. If stopping and restarting does not pick up the changes then rebuilding should be done.

**Comment by gubuntu** [comment]
Let's not make any drastic changes (like rebuilding everything). I think you can change settings.py to remove the 'staging' subdomain. I don't think existing urls with 'staging' will be problem since that url still points to the same instance. Do yo agree?

What's more of a problem are the localhost urls since they won't work from outside - any idea how to resolve that?

**Comment by gubuntu** [comment]
@rischanlab please update status and close if fixed
